### ISSUE TITLE
How to represent blood pressures?

### ISSUE THREAD

**Issue by jmandel** [argonautproject/implementation-program#1]
### Let's decide how to model blood pressures

Modeling blood pressures: so simple, yet so complicated! 
#### 1. Link Systolic + Diastolic with `Observation.component`

```
  Observation:
    code: blood pressure, loinc 55284-4
    component
        code: systolic, loinc 8480-6
        value: 120 mmHg
    component
        code: diastolic, loinc 8462-4
        value: 80 mmHg
```
#### 2. Link Systolic + Diastolic with `Observation.related`

```
  Observation:
    id: 1
    code: systolic, loinc 8480-6
    value: 120 mmHg
    related: Observation/2
  Observation:
    id: 2
    code: diastolic, loinc 8462-4
    value: 80 mmHg
    related: Observation/1
```
#### 3. No links

```
  Observation:
    code: systolic, loinc 8480-6
    value: 120 mmHg
  Observation:
    code: diastolic, loinc 8462-4
    value: 80 mmHg
```

Let's examine some advantages/disadvantages:
##### As for option 1:
- \+ Developers can query for BPs by searching at the root level (`?code= 55284-4`) or component level (`?component-code=8480-6`). 
- \+ Avoids multiple resources to represent a single blood pressure measurements
- \- Could be confusing for developers to keep `code` from `component-code` straight.

Note: we could fix the last issue by using a single search parameter that indexes
_both_ fields. This suggestion came up on today's call, and I don't think I gave it due consideration. There was, in fact, a [parameter like this (called "test")](http://www.hl7.org/fhir/2013Jan/observation.htm) back before DSTU1.
##### As for option 2:
- \+ Allow direct query at the systolic or diastolic level
- \- Requires multiple resources
- \- Requires cyclic graphs of resources (generally avoided in FHIR)
- \- Difficult to query for pairs unless a server supports `_include`
##### As for option 3:
- \- No way to link sytolic and diastolic :(

So, we'd like to take a poll and get a sense of which options people prefer. I want to be clear that this poll isn't a "formal vote", and we won't commit to implementing the "winning" result -- but we want to gather opinions in a structured way, so we can feed them back to the community, including DAF and the core FHIR spec. Ultimately Argonaut shouldn't make this decision independently; but we should be informing the community. It's likely that the FHIR specification itself will mandate a single way to do vital signs, and the decision here will be important input. For what it's worth, the default position of the FHIR core team is to strongly prefer (1).
